### ISSUE TITLE
Feature request: Make executables available from Nuget package manager console

### ISSUE THREAD

**Issue by robert-j-engdahl** [vslavik/gettext-tools-windows#4]
It shouldn't be necessary to manually setup a path.  I would love to be able to just invoke xgettext (and friends) directly from the nuget package manager console.

**Comment by vslavik** [comment]
What *I* would love to see is a bit more PRs than requests like this, especially when they are more than a bit vague.

I don't really understand what you mean by "manually setup a path" (or why you think it's "necessary") nor how you think a nuget package can affect that. Since you obviously understand what you meant better than I can and also appear to have more experience with the .NET ecosystem, you're in a much better position to make the improvement you'd like.

If you think something about the package can be improved, by all means, please submit a PR and I will happily merge it.

**Comment by robert-j-engdahl** [comment]
Cool, I'll do that right away.

**Comment by vslavik** [comment]
Closed in favor of #5.
